server:
  port: 8081

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: service_log_route
        uri: lb://log
        predicates:
        - Path=/log/**
      - id: service_device_route
        uri: lb://device
        predicates:
        - Path=/device/**

  application:
    name: gateway
  freemarker:
    check-template-location: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.0.101:8080/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

