server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: service_log_route
        uri: lb://log
        predicates:
        - Path=/log/**

  application:
    name: gateway
  freemarker:
    check-template-location: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: debug
debug: true

